# Full MEA Pipeline

Runs all six analysis stages end-to-end for every well in the dataset.

```
preprocessing → sorting → auto_merge → analyzer → auto_curation → burst_detection
```

| Stage | Task | Typical runtime |
|---|---|---|
| 1 | `preprocessing` | ~1–5 min / well |
| 2 | `sorting` | ~10–60 min / well (GPU-dependent) |
| 3 | `auto_merge` | seconds (disabled) / ~5 min (enabled) |
| 4 | `analyzer` | ~5–20 min / well |
| 5 | `auto_curation` | < 1 min / well |
| 6 | `burst_detection` | < 1 min / well |

**Configuration:** edit `pipeline_config.json` (generated on first run) to set paths,
sorting parameters, curation thresholds, and merge options.

**Re-runs are safe:** the pipeline cache skips completed wells automatically.
Changing any parameter in `pipeline_config.json` invalidates the affected task
and all downstream tasks for wells that have that config cached.

In [1]:
import sys
import time
import traceback
import logging
from pathlib import Path

import pandas as pd

_repo_root = str(Path("..").resolve())
if _repo_root not in sys.path:
    sys.path.insert(0, _repo_root)

from dataset_manager import DatasetManager
from pipeline_manager import PipelineManager, WorkItem
from pipeline_manager.task_record import TaskStatus
from pipeline_tasks import (
    PreprocessingTask,
    SortingTask,
    AutoMergeTask,
    AnalyzerTask,
    AutoCurationTask,
    BurstDetectionTask,
)
from config_manager import ConfigManager

logging.basicConfig(level=logging.WARNING)
print("Imports OK")

Imports OK

## Task chain

Inspect the registered task order and dependency graph before doing anything else.

In [2]:
ALL_TASK_CLASSES = [
    PreprocessingTask,
    SortingTask,
    AutoMergeTask,
    AnalyzerTask,
    AutoCurationTask,
    BurstDetectionTask,
]

TASK_ORDER = [cls.task_name for cls in ALL_TASK_CLASSES]

print("Pipeline execution order:")
for i, cls in enumerate(ALL_TASK_CLASSES, 1):
    deps = " → ".join(cls.dependencies) if cls.dependencies else "(none)"
    print(f"  {i}. {cls.task_name:<20s}  depends on: {deps}")

Pipeline execution order:
  1. preprocessing         depends on: (none)
  2. sorting               depends on: preprocessing
  3. auto_merge            depends on: sorting
  4. analyzer              depends on: auto_merge
  5. auto_curation         depends on: analyzer
  6. burst_detection       depends on: auto_curation

## Config

On the **first run** this cell writes `pipeline_config.json` with all task defaults and
stops — edit it to set `data_root`, `analysis_root`, and any parameters you want to
override, then re-run.

Key parameters to review before the first full run:

| Section | Key | What to set |
|---|---|---|
| `global` | `data_root` | Path to raw `.h5` recordings |
| `global` | `analysis_root` | Where all outputs are written |
| `sorting` | `sorter` | Sorter name (`kilosort4`) |
| `auto_merge` | `enabled` | `false` to skip merging |
| `auto_curation` | `enabled` | `false` to keep all units |
| `auto_curation` | `*_min` / `*_max` | Curation thresholds |

In [3]:
CONFIG_FILE = Path("../config/default_tasks_params.json")

cm = ConfigManager()
for cls in ALL_TASK_CLASSES:
    cm.register_task(cls)

if not CONFIG_FILE.exists():
    cm.generate_template(CONFIG_FILE)
    raise RuntimeError(
        f"Template written to {CONFIG_FILE}.\n"
        "Edit it — set data_root, analysis_root, and any parameters — "
        "then re-run this cell."
    )

cm.load(CONFIG_FILE)

DATA_ROOT     = Path(cm.get_global("data_root"))
ANALYSIS_ROOT = Path(cm.get_global("analysis_root"))

print(f"Config loaded: {CONFIG_FILE}")
print(f"  data_root:     {DATA_ROOT}")
print(f"  analysis_root: {ANALYSIS_ROOT}")
print()
for cls in ALL_TASK_CLASSES:
    params = cm.get_task_params(cls.task_name)
    print(f"  [{cls.task_name}]  {params}")

Config loaded: ../config/default_tasks_params.json
  data_root:     /mnt/benshalom-nas/raw_data/rbs_maxtwo_desktop/harddisk20tbV2/Sadegh_Lab/CX138
  analysis_root: ../data/analysis

  [preprocessing]  {'output_root': './preprocessed_data', 'bandpass_freq_min': 300, 'bandpass_freq_max': 3000, 'reference': 'local', 'operator': 'median', 'local_radius': [0, 250], 'dtype': 'float32', 'n_jobs': 30, 'chunk_duration': '1s', 'progress_bar': True, 'overwrite': True}
  [sorting]  {'preprocessing_output_root': './preprocessed_data', 'output_root': './spikesorted_data', 'sorter': 'kilosort4', 'docker_image': None, 'verbose': True, 'remove_existing_folder': True, 'delete_output_folder': False, 'overwrite': True, 'clean_excess_spikes': True, 'remove_empty_units': True, 'min_high_vram_gb': 14, 'high_vram_sorter_kwargs': {'batch_size_seconds': 2.0, 'clear_cache': True, 'invert_sign': True, 'cluster_downsampling': 20, 'max_cluster_subset': None, 'nblocks': 0, 'dmin': 17, 'do_correction': False}, 'low_vram_sorter_kwargs': {'batch_size_seconds': 0.5, 'clear_cache': True, 'invert_sign': True, 'cluster_downsampling': 30, 'max_cluster_subset': 50000, 'nblocks': 0, 'do_correction': False}, 'sorter_kwargs': {}}
  [auto_merge]  {'output_root': './auto_merge_data', 'sorting_output_root': './spikesorted_data', 'preprocessing_output_root': './preprocessed_data', 'enabled': False, 'presets': ['firing_rate_similarity', 'template_similarity'], 'radius_um': 50, 'n_jobs': 1}
  [analyzer]  {'output_root': './analyzer_data', 'preprocessing_output_root': './preprocessed_data', 'auto_merge_output_root': './auto_merge_data', 'radius_um': 50, 'ms_before': 1.0, 'ms_after': 2.0, 'unit_locations_method': 'monopolar_triangulation', 'n_jobs': 1}
  [auto_curation]  {'curation_output_root': './curation_data', 'analyzer_output_root': './analyzer_data', 'enabled': True, 'presence_ratio_min': 0.75, 'rp_contamination_max': 0.15, 'firing_rate_min': 0.05, 'amplitude_median_max': -20.0}
  [burst_detection]  {'curation_output_root': './curation_data', 'output_root': './burst_detection_data', 'gamma': 1.0, 'min_burstlet_participation': 0.2, 'min_absolute_rate_hz': 0.5, 'min_burst_density_hz': 1.0, 'min_relative_height': 0.1, 'extent_frac': 0.3, 'network_merge_gap_min_s': 0.75}

## 1. Scan recordings

In [4]:
ANALYSIS_ROOT.mkdir(parents=True, exist_ok=True)

dataset_mgr = DatasetManager(DATA_ROOT, ANALYSIS_ROOT)
recordings  = dataset_mgr.get_recording_by([("scan_type", "==", "Network"),
                                            ("run_id", "==", "000029")])

print(f"Found {len(recordings)} Network recording(s)")

pd.DataFrame([
    {
        "recording_key": r.cache_key,
        "date":          r.date,
        "sample_id":     r.sample_id,
        "plate_id":      r.plate_id,
        "scan_type":     r.scan_type,
        "run_id":        r.run_id,
        "n_wells":       len(r.wells),
        "size_GB":       round(r.file_size / 1e9, 2),
    }
    for r in recordings
])

Found 1 Network recording(s)

,recording_key,date,sample_id,plate_id,scan_type,run_id,n_wells,size_GB
0,CX138/260329/T003346/Network/000029,260329,CX138,T003346,Network,000029,24,18.93

## 2. Register all tasks and add wells

In [5]:
pipeline_mgr = PipelineManager(ANALYSIS_ROOT, config_provider=cm)

for cls in ALL_TASK_CLASSES:
    try:
        pipeline_mgr.register_task(cls)
        print(f"  registered: {cls.task_name!r}")
    except ValueError as e:
        print(f"  already registered: {cls.task_name!r} ({e})")

n_added   = 0
n_skipped = 0
for rec in recordings:
    if not rec.h5_recordings:
        print(f"WARNING: no h5 structure for {rec.cache_key!r} — skipping")
        n_skipped += 1
        continue
    for rec_name, well_ids in rec.h5_recordings.items():
        for well_id in well_ids:
            pipeline_mgr.add_well(rec.cache_key, f"{rec_name}/{well_id}")
            n_added += 1

print(f"\nWork units registered: {n_added}  |  Recordings skipped: {n_skipped}")

WARNING:pipeline_manager.manager:TEMPORARY FIX (issue #2): reset 3132 stale task(s) to NOT_RUN on startup.

  registered: 'preprocessing'
  registered: 'sorting'
  registered: 'auto_merge'
  registered: 'analyzer'
  registered: 'auto_curation'
  registered: 'burst_detection'

Work units registered: 24  |  Recordings skipped: 0

## 3. Pipeline status overview

The matrix below shows the current status of every (well × task) combination.
Run this cell at any time to check progress.

In [6]:
_STATUS_SYMBOL = {
    str(TaskStatus.NOT_RUN):  "\u2014",       # —
    str(TaskStatus.RUNNING):  "\u23f3",       # ⏳
    str(TaskStatus.COMPLETE): "\u2713",       # ✓
    str(TaskStatus.FAILED):   "\u2717",       # ✗
}


def _pipeline_matrix(mgr: PipelineManager) -> pd.DataFrame:
    rows = []
    for entry in mgr.entries:
        rec_name, well_id = entry.well_id.split("/", 1)
        row: dict = {
            "recording_key": entry.recording_key,
            "rec_name":      rec_name,
            "well_id":       well_id,
        }
        for task_name in TASK_ORDER:
            t = entry.tasks.get(task_name)
            status_str = str(t.status) if t else str(TaskStatus.NOT_RUN)
            row[task_name] = _STATUS_SYMBOL.get(status_str, status_str)
        rows.append(row)
    return pd.DataFrame(rows)


df_matrix = _pipeline_matrix(pipeline_mgr)
print("Legend:  \u2014 not run   \u23f3 running   \u2713 complete   \u2717 failed")
df_matrix

Legend:  — not run   ⏳ running   ✓ complete   ✗ failed

,recording_key,rec_name,well_id,preprocessing,sorting,auto_merge,analyzer,auto_curation,burst_detection
0,CX138/260327/T003346/Network/000019,rec0000,well000,✓,—,—,—,—,—
1,CX138/260327/T003346/Network/000019,rec0000,well001,✓,—,—,—,—,—
2,CX138/260327/T003346/Network/000019,rec0000,well002,✓,—,—,—,—,—
3,CX138/260327/T003346/Network/000019,rec0000,well003,✓,—,—,—,—,—
4,CX138/260327/T003346/Network/000019,rec0000,well004,✓,—,—,—,—,—
...,...,...,...,...,...,...,...,...,...
523,CX138/260404/T003346/Network/000044,rec0003,well019,—,—,—,—,—,—
524,CX138/260404/T003346/Network/000044,rec0003,well020,—,—,—,—,—,—
525,CX138/260404/T003346/Network/000044,rec0003,well021,—,—,—,—,—,—
526,CX138/260404/T003346/Network/000044,rec0003,well022,—,—,—,—,—,—
527,CX138/260404/T003346/Network/000044,rec0003,well023,—,—,—,—,—,—

## 4. Run full pipeline

`PipelineManager.get_next_task()` respects dependency order — it only returns a
task once all its upstream tasks are complete for that well.  The loop below runs
whatever is ready next until nothing remains.

**To selectively retry failed tasks** add their names to `RETRY_FAILED_TASKS`:
```python
RETRY_FAILED_TASKS = {"analyzer", "auto_curation"}
```

**To stop after a specific stage** set `STOP_AFTER_TASK`:
```python
STOP_AFTER_TASK = "sorting"   # pause before auto_merge
```

**To reset a specific well:** `pipeline_mgr.refresh(task_name, recording_key=..., well_id="rec0000/well000")`  
**To reset a full task across all wells:** `pipeline_mgr.refresh(task_name)`

In [ ]:
# ── Control knobs ────────────────────────────────────────────────────────────
RETRY_FAILED_TASKS: set[str] = set()   # e.g. {\"analyzer\", \"auto_curation\"}
STOP_AFTER_TASK:    str | None = None   # e.g. \"sorting\" to pause after sorting
# ─────────────────────────────────────────────────────────────────────────────

_task_instances: dict[str, object] = {cls.task_name: cls() for cls in ALL_TASK_CLASSES}
_rec_lookup:     dict[str, object] = {r.cache_key: r for r in recordings}
_completed_stages: list[str]       = []

# Scope get_next_task() to only the recordings loaded in this session.
# The pipeline cache may contain entries from previous runs with different
# recording keys; without this filter, those stale entries would be returned
# and fail the _rec_lookup lookup below.
_current_recording_keys = set(_rec_lookup.keys())

while True:
    work_items = pipeline_mgr.get_next_task(
        n=1, retry_failed=False, recording_keys=_current_recording_keys
    )

    # Also poll failed tasks that are explicitly marked for retry
    if not work_items and RETRY_FAILED_TASKS:
        work_items = [
            item
            for item in pipeline_mgr.get_next_task(
                n=1, retry_failed=True, recording_keys=_current_recording_keys
            )
            if item.task_name in RETRY_FAILED_TASKS
        ]

    if not work_items:
        break

    item:      WorkItem = work_items[0]
    task                = _task_instances[item.task_name]
    rec_entry           = _rec_lookup[item.recording_key]
    rec_name, well_id   = item.well_id.split("/", 1)
    params              = cm.get_task_params(item.task_name)

    print(f"\n[{item.task_name}]  {item.recording_key} / {rec_name} / {well_id}")
    pipeline_mgr.update_status(item, TaskStatus.RUNNING)

    t0 = time.perf_counter()
    try:
        output_path = task.run(
            item.recording_key,
            item.well_id,
            dataset_mgr.get_path(rec_entry),
            params,
        )
        elapsed = time.perf_counter() - t0
        pipeline_mgr.update_status(item, TaskStatus.COMPLETE, output_path=output_path)
        print(f"  ✓  {elapsed:.1f}s  → {output_path}")
        _completed_stages.append(item.task_name)
    except Exception as exc:
        elapsed = time.perf_counter() - t0
        pipeline_mgr.update_status(item, TaskStatus.FAILED, error=str(exc))
        traceback.print_exc()
        print(f"  ✗  {elapsed:.1f}s  failed: {exc}")

    if STOP_AFTER_TASK and item.task_name == STOP_AFTER_TASK:
        print(f"\nPaused after {STOP_AFTER_TASK!r} as requested.")
        break

print("\n— No more pending tasks. —")

[auto_curation]  CX138/260329/T003346/Network/000029 / rec0000 / well000
  ✓  0.3s  → curation_data/CX138/260329/T003346/Network/000029/rec0000/well000/auto_curation

[burst_detection]  CX138/260329/T003346/Network/000029 / rec0000 / well000
  ✓  0.3s  → burst_detection_data/CX138/260329/T003346/Network/000029/rec0000/well000/burst_detection

[auto_curation]  CX138/260329/T003346/Network/000029 / rec0000 / well001
  ✓  0.1s  → curation_data/CX138/260329/T003346/Network/000029/rec0000/well001/auto_curation

[burst_detection]  CX138/260329/T003346/Network/000029 / rec0000 / well001
  ✓  0.0s  → burst_detection_data/CX138/260329/T003346/Network/000029/rec0000/well001/burst_detection

[auto_curation]  CX138/260329/T003346/Network/000029 / rec0000 / well002
  ✓  0.1s  → curation_data/CX138/260329/T003346/Network/000029/rec0000/well002/auto_curation

[burst_detection]  CX138/260329/T003346/Network/000029 / rec0000 / well002
  ✓  0.0s  → burst_detection_data/CX138/260329/T003346/Network/000029/rec0000/well002/burst_detection

[auto_curation]  CX138/260329/T003346/Network/000029 / rec0000 / well003
  ✓  0.1s  → curation_data/CX138/260329/T003346/Network/000029/rec0000/well003/auto_curation

[burst_detection]  CX138/260329/T003346/Network/000029 / rec0000 / well003
  ✓  0.0s  → burst_detection_data/CX138/260329/T003346/Network/000029/rec0000/well003/burst_detection

[auto_curation]  CX138/260329/T003346/Network/000029 / rec0000 / well004
  ✓  0.1s  → curation_data/CX138/260329/T003346/Network/000029/rec0000/well004/auto_curation

[burst_detection]  CX138/260329/T003346/Network/000029 / rec0000 / well004
  ✓  0.0s  → burst_detection_data/CX138/260329/T003346/Network/000029/rec0000/well004/burst_detection

[auto_curation]  CX138/260329/T003346/Network/000029 / rec0000 / well005
  ✓  0.1s  → curation_data/CX138/260329/T003346/Network/000029/rec0000/well005/auto_curation

[burst_detection]  CX138/260329/T003346/Network/000029 / rec0000 / well005
  ✓  0.0s  → burst_detection_data/CX138/260329/T003346/Network/000029/rec0000/well005/burst_detection

[auto_curation]  CX138/260329/T003346/Network/000029 / rec0001 / well006
  ✓  0.1s  → curation_data/CX138/260329/T003346/Network/000029/rec0001/well006/auto_curation

[burst_detection]  CX138/260329/T003346/Network/000029 / rec0001 / well006
  ✓  0.0s  → burst_detection_data/CX138/260329/T003346/Network/000029/rec0001/well006/burst_detection

[analyzer]  CX138/260329/T003346/Network/000029 / rec0001 / well007

estimate_sparsity (no parallelization):   0%|          | 0/301 [00:00<?, ?it/s]

compute_waveforms (no parallelization):   0%|          | 0/301 [00:00<?, ?it/s]

noise_level (no parallelization):   0%|          | 0/20 [00:00<?, ?it/s]

/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/template_metrics.py:301: UserWarning: With less than 10 channels, multi-channel metrics might not be reliable.
  warnings.warn(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/numpy/_core/fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/numpy/_core/_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/core/analyzer_extension_core.py:1282: UserWarning: Error computing metric spread: cannot convert float NaN to integer
  warnings.warn(f"Error computing metric {metric_name}: {e}")

Compute : spike_amplitudes (no parallelization):   0%|          | 0/301 [00:00<?, ?it/s]

/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/core/analyzer_extension_core.py:1165: UserWarning: The following metrics will not be computed due to missing dependencies: ['silhouette', 'mahalanobis', 'nearest_neighbor', 'drift', 'd_prime']
  warnings.warn(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/quality/misc_metrics.py:209: RuntimeWarning: divide by zero encountered in scalar divide
  snrs[unit_id] = np.abs(amplitude) / noise
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/quality/misc_metrics.py:1026: UserWarning: Amplitude cutoff set to NaN for units [np.int64(0), np.int64(1), np.int64(3), np.int64(5), np.int64(6), np.int64(7), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(20), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(29), np.int64(30), np.int64(32), np.int64(33), np.int64(34), np.int64(36), np.int64(38), np.int64(40), np.int64(42), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(55), np.int64(56), np.int64(58), np.int64(59), np.int64(60), np.int64(62), np.int64(64), np.int64(65), np.int64(66), np.int64(67), np.int64(68), np.int64(69), np.int64(71), np.int64(72), np.int64(73), np.int64(74), np.int64(75), np.int64(76), np.int64(77), np.int64(78), np.int64(80), np.int64(81), np.int64(82), np.int64(83), np.int64(84), np.int64(85), np.int64(86), np.int64(87), np.int64(88), np.int64(90), np.int64(91), np.int64(92), np.int64(93), np.int64(95), np.int64(96), np.int64(97), np.int64(98), np.int64(100), np.int64(101), np.int64(102), np.int64(103), np.int64(104), np.int64(105), np.int64(107), np.int64(108), np.int64(109), np.int64(110), np.int64(111), np.int64(113), np.int64(114), np.int64(115), np.int64(116), np.int64(117), np.int64(118), np.int64(119), np.int64(122), np.int64(123), np.int64(125), np.int64(128), np.int64(129), np.int64(130), np.int64(133), np.int64(134), np.int64(139), np.int64(140), np.int64(142), np.int64(144), np.int64(145), np.int64(146), np.int64(147), np.int64(149), np.int64(150), np.int64(152), np.int64(153), np.int64(154), np.int64(155), np.int64(157), np.int64(158), np.int64(159), np.int64(160), np.int64(161), np.int64(162), np.int64(163), np.int64(166), np.int64(167), np.int64(170), np.int64(171), np.int64(173), np.int64(174), np.int64(176), np.int64(177), np.int64(178), np.int64(179), np.int64(180), np.int64(181), np.int64(183), np.int64(186), np.int64(187), np.int64(188), np.int64(189), np.int64(190), np.int64(191), np.int64(192), np.int64(193), np.int64(195), np.int64(197), np.int64(199), np.int64(200), np.int64(201), np.int64(202), np.int64(204), np.int64(205), np.int64(206), np.int64(207), np.int64(211), np.int64(212), np.int64(213), np.int64(214), np.int64(215), np.int64(216), np.int64(218), np.int64(219), np.int64(221), np.int64(222), np.int64(223), np.int64(224), np.int64(226), np.int64(227), np.int64(228), np.int64(229), np.int64(230), np.int64(231), np.int64(232), np.int64(234), np.int64(235), np.int64(236), np.int64(238), np.int64(239), np.int64(240), np.int64(241), np.int64(242), np.int64(243), np.int64(244), np.int64(245), np.int64(247), np.int64(248), np.int64(249), np.int64(250), np.int64(251), np.int64(252), np.int64(253), np.int64(255), np.int64(256), np.int64(257), np.int64(258), np.int64(259), np.int64(260), np.int64(261), np.int64(262), np.int64(264), np.int64(265), np.int64(266), np.int64(267), np.int64(269), np.int64(270), np.int64(271), np.int64(272), np.int64(273), np.int64(275), np.int64(276), np.int64(277), np.int64(278), np.int64(279), np.int64(280), np.int64(281), np.int64(282), np.int64(283), np.int64(284), np.int64(286), np.int64(287), np.int64(288), np.int64(289), np.int64(291), np.int64(293), np.int64(294), np.int64(295), np.int64(297), np.int64(298), np.int64(301), np.int64(302), np.int64(303), np.int64(304), np.int64(305), np.int64(306), np.int64(308), np.int64(309), np.int64(310), np.int64(311), np.int64(312), np.int64(313), np.int64(315), np.int64(316), np.int64(317), np.int64(318), np.int64(319), np.int64(320), np.int64(321), np.int64(322), np.int64(323), np.int64(324), np.int64(326), np.int64(327), np.int64(328), np.int64(330), np.int64(332), np.int64(333), np.int64(334), np.int64(335), np.int64(337), np.int64(338), np.int64(339), np.int64(340), np.int64(341), np.int64(342), np.int64(343)]: too few spikes (< 500).
  warnings.warn(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/quality/misc_metrics.py:1881: UserWarning: No bin is selected to test cutoff. Please increase low_quantile. Setting noise cutoff and ratio to NaN
  warnings.warn(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/quality/misc_metrics.py:1892: UserWarning: No bin is selected as the reference region. Please increase high_quantile. Setting noise cutoff to NaN
  warnings.warn(

  ✓  47.1s  → analyzer_data/CX138/260329/T003346/Network/000029/rec0001/well007/analyzer

[auto_curation]  CX138/260329/T003346/Network/000029 / rec0001 / well007
  ✓  0.1s  → curation_data/CX138/260329/T003346/Network/000029/rec0001/well007/auto_curation

[burst_detection]  CX138/260329/T003346/Network/000029 / rec0001 / well007
  ✓  0.0s  → burst_detection_data/CX138/260329/T003346/Network/000029/rec0001/well007/burst_detection

[preprocessing]  CX138/260329/T003346/Network/000029 / rec0001 / well008
The h5 compression library for Maxwell is already located in /home/yuxin/hdf5_plugin_path_maxwell/libcompression.so!
write_zarr_recording
engine=process - n_jobs=30 - samples_per_chunk=10,000 - chunk_memory=38.22 MiB - total_memory=1.12 GiB - chunk_duration=1.00s

write_zarr_recording (workers: 30 processes fork):   0%|          | 0/301 [00:00<?, ?it/s]

  ✓  57.2s  → preprocessed_data/CX138/260329/T003346/Network/000029/rec0001/well008/preprocessed.zarr

[sorting]  CX138/260329/T003346/Network/000029 / rec0001 / well008

/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/torch/cuda/__init__.py:65: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]

write_binary_recording (no parallelization):   0%|          | 0/301 [00:00<?, ?it/s]

INFO:kilosort.run_kilosort:
INFO:kilosort.run_kilosort:Computing preprocessing variables.
INFO:kilosort.run_kilosort:----------------------------------------
INFO:kilosort.run_kilosort:N samples: 3000400
INFO:kilosort.run_kilosort:N seconds: 300.04
INFO:kilosort.run_kilosort:N batches: 151
INFO:kilosort.run_kilosort:Preprocessing filters computed in 0.57s; total 0.57s
DEBUG:kilosort.run_kilosort:hp_filter shape: torch.Size([30122])
DEBUG:kilosort.run_kilosort:whiten_mat shape: torch.Size([1002, 1002])
DEBUG:kilosort.run_kilosort:First batch min, max: (np.float32(-6.932638), np.float32(24.045195))
INFO:kilosort.run_kilosort:
INFO:kilosort.run_kilosort:Resource usage after preprocessing
INFO:kilosort.run_kilosort:********************************************************
INFO:kilosort.run_kilosort:CPU usage:     3.20 %
INFO:kilosort.run_kilosort:Mem used:     29.30 %     |      18.33 GB
INFO:kilosort.run_kilosort:Mem avail:    44.21 / 62.54 GB
INFO:kilosort.run_kilosort:------------------------------------------------------
INFO:kilosort.run_kilosort:GPU usage:    63.00 %
INFO:kilosort.run_kilosort:GPU memory:    6.71 %     |      2.10   /    31.36 GB
INFO:kilosort.run_kilosort:Allocated:     0.04 %     |      0.01   /    31.36 GB
INFO:kilosort.run_kilosort:Max alloc:     3.65 %     |      1.14   /    31.36 GB
INFO:kilosort.run_kilosort:********************************************************
INFO:kilosort.run_kilosort:
INFO:kilosort.run_kilosort:Computing drift correction.
INFO:kilosort.run_kilosort:----------------------------------------
INFO:kilosort.datashift:nblocks = 0, skipping drift correction
INFO:kilosort.run_kilosort:drift computed in 0.00s; total 1.03s
DEBUG:kilosort.run_kilosort:

|===========================================================================|
|                  PyTorch CUDA memory summary, device ID 0                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 0            |        cudaMalloc retries: 0         |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      |  12360 KiB |  12360 KiB |  14729 MiB |  14717 MiB |
|---------------------------------------------------------------------------|
| Active memory         |  12360 KiB |  12360 KiB |  14729 MiB |  14717 MiB |
|---------------------------------------------------------------------------|
| Requested memory      |  12359 KiB |  12359 KiB |  14716 MiB |  14704 MiB |
|---------------------------------------------------------------------------|
| GPU reserved memory   |   1418 MiB |   1418 MiB |   1418 MiB |      0 B   |
|---------------------------------------------------------------------------|
| Non-releasable memory |  10168 KiB |  10168 KiB |   5623 MiB |   5613 MiB |
|---------------------------------------------------------------------------|
| Allocations           |       3    |       3    |   18200    |   18197    |
|---------------------------------------------------------------------------|
| Active allocs         |       3    |       3    |   18200    |   18197    |
|---------------------------------------------------------------------------|
| GPU reserved segments |       8    |       8    |       8    |       0    |
|---------------------------------------------------------------------------|
| Non-releasable allocs |       4    |       4    |    5603    |    5599    |
|---------------------------------------------------------------------------|
| Oversize allocations  |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Oversize GPU segments |       0    |       0    |       0    |       0    |
|===========================================================================|


INFO:kilosort.run_kilosort:
INFO:kilosort.run_kilosort:Resource usage after drift correction
INFO:kilosort.run_kilosort:********************************************************
INFO:kilosort.run_kilosort:CPU usage:     7.10 %
INFO:kilosort.run_kilosort:Mem used:     29.20 %     |      18.26 GB
INFO:kilosort.run_kilosort:Mem avail:    44.28 / 62.54 GB
INFO:kilosort.run_kilosort:------------------------------------------------------
INFO:kilosort.run_kilosort:GPU usage:    63.00 %
INFO:kilosort.run_kilosort:GPU memory:    6.71 %     |      2.10   /    31.36 GB
INFO:kilosort.run_kilosort:Allocated:     0.04 %     |      0.01   /    31.36 GB
INFO:kilosort.run_kilosort:Max alloc:     0.04 %     |      0.01   /    31.36 GB
INFO:kilosort.run_kilosort:********************************************************
INFO:kilosort.run_kilosort:
INFO:kilosort.run_kilosort:Extracting spikes using templates
INFO:kilosort.run_kilosort:----------------------------------------
INFO:kilosort.spikedetect:Re-computing universal templates from data.

Skipping drift correction.

INFO:kilosort.spikedetect:Number of universal templates: 58563
INFO:kilosort.spikedetect:Detecting spikes...
  0%|          | 0/151 [00:00<?, ?it/s]DEBUG:kilosort.spikedetect:
DEBUG:kilosort.spikedetect:Batch 0 of 150 (0.0%)
DEBUG:kilosort.spikedetect:********************************************************
DEBUG:kilosort.spikedetect:CPU usage:     5.50 %
DEBUG:kilosort.spikedetect:Mem used:     30.90 %     |      19.31 GB
DEBUG:kilosort.spikedetect:Mem avail:    43.23 / 62.54 GB
DEBUG:kilosort.spikedetect:------------------------------------------------------
DEBUG:kilosort.spikedetect:GPU usage:     0.00 %
DEBUG:kilosort.spikedetect:GPU memory:    6.72 %     |      2.11   /    31.36 GB
DEBUG:kilosort.spikedetect:Allocated:     0.07 %     |      0.02   /    31.36 GB
DEBUG:kilosort.spikedetect:Max alloc:     3.65 %     |      1.14   /    31.36 GB
DEBUG:kilosort.spikedetect:********************************************************
100%|██████████| 151/151 [01:07<00:00,  2.25it/s]
DEBUG:kilosort.spikedetect:
DEBUG:kilosort.spikedetect:Batch 150 of 150 (99.3%)
DEBUG:kilosort.spikedetect:********************************************************
DEBUG:kilosort.spikedetect:CPU usage:     3.50 %
DEBUG:kilosort.spikedetect:Mem used:     31.20 %     |      19.54 GB
DEBUG:kilosort.spikedetect:Mem avail:    43.00 / 62.54 GB
DEBUG:kilosort.spikedetect:------------------------------------------------------
DEBUG:kilosort.spikedetect:GPU usage:    51.00 %
DEBUG:kilosort.spikedetect:GPU memory:    2.88 %     |      0.90   /    31.36 GB
DEBUG:kilosort.spikedetect:Allocated:     0.31 %     |      0.10   /    31.36 GB
DEBUG:kilosort.spikedetect:Max alloc:    21.33 %     |      6.69   /    31.36 GB
DEBUG:kilosort.spikedetect:********************************************************
INFO:kilosort.run_kilosort:209383 spikes extracted in 72.51s; total 73.55s
DEBUG:kilosort.run_kilosort:st0 shape: (209383, 6)
DEBUG:kilosort.run_kilosort:tF shape: torch.Size([209383, 10, 6])
INFO:kilosort.run_kilosort:
INFO:kilosort.run_kilosort:Resource usage after spike detect (univ)
INFO:kilosort.run_kilosort:********************************************************
INFO:kilosort.run_kilosort:CPU usage:     0.00 %
INFO:kilosort.run_kilosort:Mem used:     29.90 %     |      18.71 GB
INFO:kilosort.run_kilosort:Mem avail:    43.83 / 62.54 GB
INFO:kilosort.run_kilosort:------------------------------------------------------
INFO:kilosort.run_kilosort:GPU usage:    51.00 %
INFO:kilosort.run_kilosort:GPU memory:    2.88 %     |      0.90   /    31.36 GB
INFO:kilosort.run_kilosort:Allocated:     0.07 %     |      0.02   /    31.36 GB
INFO:kilosort.run_kilosort:Max alloc:    21.33 %     |      6.69   /    31.36 GB
INFO:kilosort.run_kilosort:********************************************************
DEBUG:kilosort.run_kilosort:
DEBUG:kilosort.run_kilosort:--------------------
DEBUG:kilosort.run_kilosort:Process thread count: 88
DEBUG:kilosort.run_kilosort:num torch threads: 24
DEBUG:kilosort.run_kilosort:--------------------

INFO:kilosort.run_kilosort:
INFO:kilosort.run_kilosort:First clustering
INFO:kilosort.run_kilosort:----------------------------------------
  0%|          | 0/23 [00:00<?, ?it/s]DEBUG:kilosort.clustering_qr:Center 12 | Xd shape: torch.Size([4, 66]) | ntemp: 6
DEBUG:kilosort.clustering_qr:Center 13 | Xd shape: torch.Size([55, 72]) | ntemp: 20
DEBUG:kilosort.clustering_qr:Center 14 | Xd shape: torch.Size([135, 66]) | ntemp: 22
DEBUG:kilosort.clustering_qr:Center 15 | Xd shape: torch.Size([89, 72]) | ntemp: 8
DEBUG:kilosort.clustering_qr:Center 16 | Xd shape: torch.Size([17, 60]) | ntemp: 2
DEBUG:kilosort.clustering_qr:Center 17 | Xd shape: torch.Size([6, 66]) | ntemp: 3
DEBUG:kilosort.clustering_qr:Center 18 | Xd shape: torch.Size([11, 60]) | ntemp: 2
DEBUG:kilosort.clustering_qr:Center 19 | Xd shape: torch.Size([241, 66]) | ntemp: 4
DEBUG:kilosort.clustering_qr:Center 20 | Xd shape: torch.Size([1272, 78]) | ntemp: 20
DEBUG:kilosort.clustering_qr:
DEBUG:kilosort.clustering_qr:Cluster center: 21 (10/814)
DEBUG:kilosort.clustering_qr:********************************************************
DEBUG:kilosort.clustering_qr:CPU usage:    11.40 %
DEBUG:kilosort.clustering_qr:Mem used:     30.40 %     |      19.00 GB
DEBUG:kilosort.clustering_qr:Mem avail:    43.54 / 62.54 GB
DEBUG:kilosort.clustering_qr:------------------------------------------------------
DEBUG:kilosort.clustering_qr:GPU usage:    18.00 %
DEBUG:kilosort.clustering_qr:GPU memory:    2.64 %     |      0.83   /    31.36 GB
DEBUG:kilosort.clustering_qr:Allocated:     0.07 %     |      0.02   /    31.36 GB
DEBUG:kilosort.clustering_qr:Max alloc:     0.08 %     |      0.03   /    31.36 GB
DEBUG:kilosort.clustering_qr:********************************************************
DEBUG:kilosort.clustering_qr:Center 21 | Xd shape: torch.Size([545, 84]) | ntemp: 23
DEBUG:kilosort.clustering_qr:
DEBUG:kilosort.clustering_qr:clustering_qr.run, after iclust
DEBUG:kilosort.clustering_qr:********************************************************
DEBUG:kilosort.clustering_qr:CPU usage:     6.70 %
DEBUG:kilosort.clustering_qr:Mem used:     30.40 %     |      19.00 GB
DEBUG:kilosort.clustering_qr:Mem avail:    43.54 / 62.54 GB
DEBUG:kilosort.clustering_qr:------------------------------------------------------
DEBUG:kilosort.clustering_qr:GPU usage:    18.00 %
DEBUG:kilosort.clustering_qr:GPU memory:    2.64 %     |      0.83   /    31.36 GB
DEBUG:kilosort.clustering_qr:Allocated:     0.07 %     |      0.02   /    31.36 GB
DEBUG:kilosort.clustering_qr:Max alloc:     0.08 %     |      0.03   /    31.36 GB
DEBUG:kilosort.clustering_qr:********************************************************
DEBUG:kilosort.clustering_qr:Center 22 | Xd shape: torch.Size([1299, 72]) | ntemp: 11
DEBUG:kilosort.clustering_qr:Center 25 | Xd shape: torch.Size([346, 78]) | ntemp: 19
DEBUG:kilosort.clustering_qr:Center 26 | Xd shape: torch.Size([353, 90]) | ntemp: 19
DEBUG:kilosort.clustering_qr:Center 27 | Xd shape: torch.Size([60, 90]) | ntemp: 4
DEBUG:kilosort.clustering_qr:Center 32 | Xd shape: torch.Size([18, 66]) | ntemp: 11
DEBUG:kilosort.clustering_qr:Center 33 | Xd shape: torch.Size([22, 72]) | ntemp: 13
DEBUG:kilosort.clustering_qr:Center 34 | Xd shape: torch.Size([2, 60]) | ntemp: 4
DEBUG:kilosort.clustering_qr:Center 39 | Xd shape: torch.Size([37, 84]) | ntemp: 11
DEBUG:kilosort.clustering_qr:Center 40 | Xd shape: torch.Size([130, 78]) | ntemp: 20
DEBUG:kilosort.clustering_qr:
DEBUG:kilosort.clustering_qr:Cluster center: 41 (20/814)
DEBUG:kilosort.clustering_qr:********************************************************
DEBUG:kilosort.clustering_qr:CPU usage:     8.00 %
DEBUG:kilosort.clustering_qr:Mem used:     30.40 %     |      19.00 GB
DEBUG:kilosort.clustering_qr:Mem avail:    43.54 / 62.54 GB
DEBUG:kilosort.clustering_qr:------------------------------------------------------
DEBUG:kilosort.clustering_qr:GPU usage:    29.00 %
DEBUG:kilosort.clustering_qr:GPU memory:    2.64 %     |      0.83   /    31.36 GB
DEBUG:kilosort.clustering_qr:Allocated:     0.07 %     |      0.02   /    31.36 GB
DEBUG:kilosort.clustering_qr:Max alloc:     0.08 %     |      0.03   /    31.36 GB
DEBUG:kilosort.clustering_qr:********************************************************
DEBUG:kilosort.clustering_qr:Center 41 | Xd shape: torch.Size([283, 72]) | ntemp: 12
DEBUG:kilosort.clustering_qr:
DEBUG:kilosort.clustering_qr:clustering_qr.run, after iclust
DEBUG:kilosort.clustering_qr:********************************************************
DEBUG:kilosort.clustering_qr:CPU usage:    37.50 %
DEBUG:kilosort.clustering_qr:Mem used:     30.40 %     |      19.00 GB
DEBUG:kilosort.clustering_qr:Mem avail:    43.54 / 62.54 GB
DEBUG:kilosort.clustering_qr:------------------------------------------------------
DEBUG:kilosort.clustering_qr:GPU usage:    29.00 %
DEBUG:kilosort.clustering_qr:GPU memory:    2.64 %     |      0.83   /    31.36 GB
DEBUG:kilosort.clustering_qr:Allocated:     0.07 %     |      0.02   /    31.36 GB
DEBUG:kilosort.clustering_qr:Max alloc:     0.08 %     |      0.03   /    31.36 GB
DEBUG:kilosort.clustering_qr:********************************************************
DEBUG:kilosort.clustering_qr:Center 44 | Xd shape: torch.Size([95, 72]) | ntemp: 18
DEBUG:kilosort.clustering_qr:Center 45 | Xd shape: torch.Size([192, 66]) | ntemp: 20
DEBUG:kilosort.clustering_qr:Center 46 | Xd shape: torch.Size([146, 60]) | ntemp: 4
DEBUG:kilosort.clustering_qr:Center 50 | Xd shape: torch.Size([331, 90]) | ntemp: 14
DEBUG:kilosort.clustering_qr:Center 51 | Xd shape: torch.Size([504, 96]) | ntemp: 20
DEBUG:kilosort.clustering_qr:Center 52 | Xd shape: torch.Size([85, 72]) | ntemp: 8
DEBUG:kilosort.clustering_qr:Center 56 | Xd shape: torch.Size([4, 60]) | ntemp: 2
DEBUG:kilosort.clustering_qr:Center 57 | Xd shape: torch.Size([45, 66]) | ntemp: 14
DEBUG:kilosort.clustering_qr:Center 58 | Xd shape: torch.Size([636, 66]) | ntemp: 14
DEBUG:kilosort.clustering_qr:
DEBUG:kilosort.clustering_qr:Cluster center: 59 (30/814)
DEBUG:kilosort.clustering_qr:********************************************************
DEBUG:kilosort.clustering_qr:CPU usage:    40.60 %
DEBUG:kilosort.clustering_qr:Mem used:     30.40 %     |      19.00 GB
DEBUG:kilosort.clustering_qr:Mem avail:    43.54 / 62.54 GB
DEBUG:kilosort.clustering_qr:------------------------------------------------------
DEBUG:kilosort.clustering_qr:GPU usage:    29.00 %
DEBUG:kilosort.clustering_qr:GPU memory:    2.64 %     |      0.83   /    31.36 GB
DEBUG:kilosort.clustering_qr:Allocated:     0.07 %     |      0.02   /    31.36 GB
DEBUG:kilosort.clustering_qr:Max alloc:     0.08 %     |      0.03   /    31.36 GB
DEBUG:kilosort.clustering_qr:********************************************************
DEBUG:kilosort.clustering_qr:Center 59 | Xd shape: torch.Size([95, 66]) | ntemp: 3
DEBUG:kilosort.clustering_qr:
DEBUG:kilosort.clustering_qr:clustering_qr.run, after iclust
DEBUG:kilosort.clustering_qr:********************************************************
DEBUG:kilosort.clustering_qr:CPU usage:    43.80 %
DEBUG:kilosort.clustering_qr:Mem used:     30.40 %     |      19.00 GB
DEBUG:kilosort.clustering_qr:Mem avail:    43.54 / 62.54 GB
DEBUG:kilosort.clustering_qr:------------------------------------------------------
DEBUG:kilosort.clustering_qr:GPU usage:    29.00 %
DEBUG:kilosort.clustering_qr:GPU memory:    2.64 %     |      0.83   /    31.36 GB
DEBUG:kilosort.clustering_qr:Allocated:     0.07 %     |      0.02   /    31.36 GB
DEBUG:kilosort.clustering_qr:Max alloc:     0.08 %     |      0.03   /    31.36 GB
DEBUG:kilosort.clustering_qr:********************************************************
  4%|▍         | 1/23 [00:00<00:11,  1.91it/s]DEBUG:kilosort.clustering_qr:Center 70 | Xd shape: torch.Size([1, 78]) | ntemp: 7
DEBUG:kilosort.clustering_qr:Center 71 | Xd shape: torch.Size([49, 84]) | ntemp: 20
DEBUG:kilosort.clustering_qr:Center 72 | Xd shape: torch.Size([101, 84]) | ntemp: 14
DEBUG:kilosort.clustering_qr:Center 75 | Xd shape: torch.Size([91, 78]) | ntemp: 11
DEBUG:kilosort.clustering_qr:Center 76 | Xd shape: torch.Size([241, 66]) | ntemp: 12
DEBUG:kilosort.clustering_qr:Center 77 | Xd shape: torch.Size([106, 84]) | ntemp: 9
DEBUG:kilosort.clustering_qr:Center 78 | Xd shape: torch.Size([67, 78]) | ntemp: 16
DEBUG:kilosort.clustering_qr:Center 79 | Xd shape: torch.Size([376, 84]) | ntemp: 24
DEBUG:kilosort.clustering_qr:Center 80 | Xd shape: torch.Size([375, 96]) | ntemp: 20
DEBUG:kilosort.clustering_qr:
DEBUG:kilosort.clustering_qr:Cluster center: 81 (40/814)
DEBUG:kilosort.clustering_qr:********************************************************
DEBUG:kilosort.clustering_qr:CPU usage:    38.30 %
DEBUG:kilosort.clustering_qr:Mem used:     30.40 %     |      19.00 GB
DEBUG:kilosort.clustering_qr:Mem avail:    43.54 / 62.54 GB
DEBUG:kilosort.clustering_qr:------------------------------------------------------
DEBUG:kilosort.clustering_qr:GPU usage:    29.00 %
DEBUG:kilosort.clustering_qr:GPU memory:    2.64 %     |      0.83   /    31.36 GB
DEBUG:kilosort.clustering_qr:Allocated:     0.07 %     |      0.02   /    31.36 GB
DEBUG:kilosort.clustering_qr:Max alloc:     0.08 %     |      0.03   /    31.36 GB
DEBUG:kilosort.clustering_qr:********************************************************
DEBUG:kilosort.clustering_qr:Center 81 | Xd shape: torch.Size([571, 114]) | ntemp: 17
DEBUG:kilosort.clustering_qr:
DEBUG:kilosort.clustering_qr:clustering_qr.run, after iclust
DEBUG:kilosort.clustering_qr:********************************************************
DEBUG:kilosort.clustering_qr:CPU usage:    28.60 %
DEBUG:kilosort.clustering_qr:Mem used:     30.40 %     |      19.00 GB
DEBUG:kilosort.clustering_qr:Mem avail:    43.54 / 62.54 GB
DEBUG:kilosort.clustering_qr:------------------------------------------------------
DEBUG:kilosort.clustering_qr:GPU usage:    29.00 %
DEBUG:kilosort.clustering_qr:GPU memory:    2.64 %     |      0.83   /    31.36 GB
DEBUG:kilosort.clustering_qr:Allocated:     0.07 %     |      0.02   /    31.36 GB
DEBUG:kilosort.clustering_qr:Max alloc:     0.08 %     |      0.03   /    31.36 GB
DEBUG:kilosort.clustering_qr:********************************************************
DEBUG:kilosort.clustering_qr:Center 82 | Xd shape: torch.Size([115, 84]) | ntemp: 8
DEBUG:kilosort.clustering_qr:Center 83 | Xd shape: torch.Size([14, 78]) | ntemp: 10
DEBUG:kilosort.clustering_qr:Center 84 | Xd shape: torch.Size([478, 84]) | ntemp: 20
DEBUG:kilosort.clustering_qr:Center 85 | Xd shape: torch.Size([39, 84]) | ntemp: 12
DEBUG:kilosort.clustering_qr:Center 86 | Xd shape: torch.Size([508, 72]) | ntemp: 15
DEBUG:kilosort.clustering_qr:Center 87 | Xd shape: torch.Size([398, 78]) | ntemp: 16
DEBUG:kilosort.clustering_qr:Center 88 | Xd shape: torch.Size([56, 72]) | ntemp: 3
DEBUG:kilosort.clustering_qr:Center 91 | Xd shape: torch.Size([1019, 60]) | ntemp: 4
DEBUG:kilosort.clustering_qr:Center 92 | Xd shape: torch.Size([3, 60]) | ntemp: 2
DEBUG:kilosort.clustering_qr:
DEBUG:kilosort.clustering_qr:Cluster center: 95 (50/814)
DEBUG:kilosort.clustering_qr:********************************************************
DEBUG:kilosort.clustering_qr:CPU usage:     4.50 %
DEBUG:kilosort.clustering_qr:Mem used:     30.40 %     |      19.00 GB
DEBUG:kilosort.clustering_qr:Mem avail:    43.54 / 62.54 GB
DEBUG:kilosort.clustering_qr:------------------------------------------------------
DEBUG:kilosort.clustering_qr:GPU usage:    29.00 %
DEBUG:kilosort.clustering_qr:GPU memory:    2.64 %     |      0.83   /    31.36 GB
DEBUG:kilosort.clustering_qr:Allocated:     0.07 %     |      0.02   /    31.36 GB
DEBUG:kilosort.clustering_qr:Max alloc:     0.08 %     |      0.03   /    31.36 GB
DEBUG:kilosort.clustering_qr:********************************************************
DEBUG:kilosort.clustering_qr:Center 95 | Xd shape: torch.Size([25, 84]) | ntemp: 4
DEBUG:kilosort.clustering_qr:
DEBUG:kilosort.clustering_qr:clustering_qr.run, after iclust
DEBUG:kilosort.clustering_qr:********************************************************
DEBUG:kilosort.clustering_qr:CPU usage:    38.50 %
DEBUG:kilosort.clustering_qr:Mem used:     30.40 %     |      19.00 GB
DEBUG:kilosort.clustering_qr:Mem avail:    43.54 / 62.54 GB
DEBUG:kilosort.clustering_qr:------------------------------------------------------
DEBUG:kilosort.clustering_qr:GPU usage:    29.00 %
DEBUG:kilosort.clustering_qr:GPU memory:    2.64 %     |      0.83   /    31.36 GB
DEBUG:kilosort.clustering_qr:Allocated:     0.07 %     |      0.02   /    31.36 GB
DEBUG:kilosort.clustering_qr:Max alloc:     0.08 %     |      0.03   /    31.36 GB
DEBUG:kilosort.clustering_qr:********************************************************
DEBUG:kilosort.clustering_qr:Center 96 | Xd shape: torch.Size([108, 84]) | ntemp: 19
DEBUG:kilosort.clustering_qr:Center 97 | Xd shape: torch.Size([428, 84]) | ntemp: 18
DEBUG:kilosort.clustering_qr:Center 99 | Xd shape: torch.Size([2, 66]) | ntemp: 2
DEBUG:kilosort.clustering_qr:Center 100 | Xd shape: torch.Size([41, 90]) | ntemp: 18
DEBUG:kilosort.clustering_qr:Center 101 | Xd shape: torch.Size([558, 84]) | ntemp: 19
DEBUG:kilosort.clustering_qr:Center 102 | Xd shape: torch.Size([403, 78]) | ntemp: 5
DEBUG:kilosort.clustering_qr:Center 103 | Xd shape: torch.Size([119, 66]) | ntemp: 8
DEBUG:kilosort.clustering_qr:Center 104 | Xd shape: torch.Size([150, 66]) | ntemp: 5
DEBUG:kilosort.clustering_qr:Center 106 | Xd shape: torch.Size([181, 78]) | ntemp: 17
DEBUG:kilosort.clustering_qr:
DEBUG:kilosort.clustering_qr:Cluster center: 107 (60/814)
DEBUG:kilosort.clustering_qr:********************************************************
DEBUG:kilosort.clustering_qr:CPU usage:    40.80 %
DEBUG:kilosort.clustering_qr:Mem used:     30.40 %     |      19.00 GB
DEBUG:kilosort.clustering_qr:Mem avail:    43.54 / 62.54 GB
DEBUG:kilosort.clustering_qr:------------------------------------------------------
DEBUG:kilosort.clustering_qr:GPU usage:    29.00 %
DEBUG:kilosort.clustering_qr:GPU memory:    2.64 %     |      0.83   /    31.36 GB
DEBUG:kilosort.clustering_qr:Allocated:     0.07 %     |      0.02   /    31.36 GB
DEBUG:kilosort.clustering_qr:Max alloc:     0.08 %     |      0.03   /    31.36 GB
DEBUG:kilosort.clustering_qr:********************************************************
DEBUG:kilosort.clustering_qr:Center 107 | Xd shape: torch.Size([392, 78]) | ntemp: 19
DEBUG:kilosort.clustering_qr:
DEBUG:kilosort.clustering_qr:clustering_qr.run, after iclust
DEBUG:kilosort.clustering_qr:********************************************************
DEBUG:kilosort.clustering_qr:CPU usage:    40.00 %
DEBUG:kilosort.clustering_qr:Mem used:     30.40 %     |      19.00 GB
DEBUG:kilosort.clustering_qr:Mem avail:    43.54 / 62.54 GB
DEBUG:kilosort.clustering_qr:------------------------------------------------------
DEBUG:kilosort.clustering_qr:GPU usage:    29.00 %
DEBUG:kilosort.clustering_qr:GPU memory:    2.64 %     |      0.83   /    31.36 GB
DEBUG:kilosort.clustering_qr:Allocated:     0.07 %     |      0.02   /    31.36 GB
DEBUG:kilosort.clustering_qr:Max alloc:     0.08 %     |      0.03   /    31.36 GB
DEBUG:kilosort.clustering_qr:********************************************************
DEBUG:kilosort.clustering_qr:Center 108 | Xd shape: torch.Size([27, 72]) | ntemp: 6
DEBUG:kilosort.clustering_qr:Center 113 | Xd shape: torch.Size([30, 60]) | ntemp: 3
DEBUG:kilosort.clustering_qr:Center 114 | Xd shape: torch.Size([319, 84]) | ntemp: 19
DEBUG:kilosort.clustering_qr:Center 115 | Xd shape: torch.Size([126, 84]) | ntemp: 16
  9%|▊         | 2/23 [00:00<00:07,  2.77it/s]DEBUG:kilosort.clustering_qr:Center 123 | Xd shape: torch.Size([1, 66]) | ntemp: 11
DEBUG:kilosort.clustering_qr:Center 124 | Xd shape: torch.Size([126, 72]) | ntemp: 16
DEBUG:kilosort.clustering_qr:Center 125 | Xd shape: torch.Size([197, 60]) | ntemp: 9
DEBUG:kilosort.clustering_qr:Center 128 | Xd shape: torch.Size([67, 72]) | ntemp: 8
DEBUG:kilosort.clustering_qr:Center 129 | Xd shape: torch.Size([665, 102]) | ntemp: 20
DEBUG:kilosort.clustering_qr:
DEBUG:kilosort.clustering_qr:Cluster center: 130 (70/814)
DEBUG:kilosort.clustering_qr:********************************************************
DEBUG:kilosort.clustering_qr:CPU usage:    42.30 %
DEBUG:kilosort.clustering_qr:Mem used:     30.40 %     |      19.00 GB
DEBUG:kilosort.clustering_qr:Mem avail:    43.54 / 62.54 GB
DEBUG:kilosort.clustering_qr:------------------------------------------------------
DEBUG:kilosort.clustering_qr:GPU usage:    29.00 %
DEBUG:kilosort.clustering_qr:GPU memory:    2.64 %     |      0.83   /    31.36 GB
DEBUG:kilosort.clustering_qr:Allocated:     0.07 %     |      0.02   /    31.36 GB
DEBUG:kilosort.clustering_qr:Max alloc:     0.08 %     |      0.03   /    31.36 GB
DEBUG:kilosort.clustering_qr:********************************************************
DEBUG:kilosort.clustering_qr:Center 130 | Xd shape: torch.Size([489, 96]) | ntemp: 13
DEBUG:kilosort.clustering_qr:

kilosort4 run time 95.88s

/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/core/basesorting.py:384: UserWarning: The registered recording will not be persistent on disk, but only available in memory
  warnings.warn("The registered recording will not be persistent on disk, but only available in memory")

  ✓  126.9s  → spikesorted_data/CX138/260329/T003346/Network/000029/rec0001/well008/sorter_output

[auto_merge]  CX138/260329/T003346/Network/000029 / rec0001 / well008
  ✓  0.1s  → auto_merge_data/CX138/260329/T003346/Network/000029/rec0001/well008/auto_merge

[analyzer]  CX138/260329/T003346/Network/000029 / rec0001 / well008

estimate_sparsity (no parallelization):   0%|          | 0/301 [00:00<?, ?it/s]

compute_waveforms (no parallelization):   0%|          | 0/301 [00:00<?, ?it/s]

noise_level (no parallelization):   0%|          | 0/20 [00:00<?, ?it/s]

/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/template_metrics.py:301: UserWarning: With less than 10 channels, multi-channel metrics might not be reliable.
  warnings.warn(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/template/metrics.py:936: OptimizeWarning: Covariance of the parameters could not be estimated
  popt, _ = curve_fit(

Compute : spike_amplitudes (no parallelization):   0%|          | 0/301 [00:00<?, ?it/s]

/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/core/analyzer_extension_core.py:1165: UserWarning: The following metrics will not be computed due to missing dependencies: ['silhouette', 'mahalanobis', 'nearest_neighbor', 'drift', 'd_prime']
  warnings.warn(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/numpy/_core/_methods.py:219: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/numpy/_core/_methods.py:178: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean,
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/numpy/_core/_methods.py:211: RuntimeWarning: invalid value encountered in divide
  ret = ret.dtype.type(ret / rcount)
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/quality/misc_metrics.py:1026: UserWarning: Amplitude cutoff set to NaN for units [np.int64(0), np.int64(2), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(28), np.int64(29), np.int64(30), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(37), np.int64(39), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55), np.int64(56), np.int64(57), np.int64(60), np.int64(61), np.int64(62), np.int64(64), np.int64(66), np.int64(67), np.int64(69), np.int64(70), np.int64(71), np.int64(74), np.int64(75), np.int64(77), np.int64(78), np.int64(80), np.int64(81), np.int64(84), np.int64(85), np.int64(86), np.int64(87), np.int64(88), np.int64(90), np.int64(92), np.int64(93), np.int64(94), np.int64(95), np.int64(96), np.int64(98), np.int64(99), np.int64(100), np.int64(101), np.int64(102), np.int64(103), np.int64(104), np.int64(105), np.int64(108), np.int64(109), np.int64(110), np.int64(111), np.int64(114), np.int64(115), np.int64(116), np.int64(117), np.int64(118), np.int64(119), np.int64(121), np.int64(122), np.int64(125), np.int64(126), np.int64(127), np.int64(128), np.int64(130), np.int64(131), np.int64(132), np.int64(133), np.int64(134), np.int64(135), np.int64(136), np.int64(138), np.int64(139), np.int64(140), np.int64(141), np.int64(143), np.int64(144), np.int64(145), np.int64(147), np.int64(149), np.int64(150), np.int64(152), np.int64(156), np.int64(157), np.int64(159), np.int64(160), np.int64(161), np.int64(162), np.int64(163), np.int64(165), np.int64(168), np.int64(170), np.int64(172), np.int64(174), np.int64(175), np.int64(177), np.int64(179), np.int64(180), np.int64(181), np.int64(182), np.int64(184), np.int64(185), np.int64(188), np.int64(189), np.int64(190), np.int64(194), np.int64(195), np.int64(197), np.int64(198), np.int64(199), np.int64(200), np.int64(201), np.int64(202), np.int64(204), np.int64(205), np.int64(206), np.int64(207), np.int64(208), np.int64(209), np.int64(210), np.int64(211), np.int64(212), np.int64(213), np.int64(214), np.int64(215), np.int64(217), np.int64(219), np.int64(220), np.int64(221), np.int64(222), np.int64(224), np.int64(225), np.int64(228), np.int64(229), np.int64(231), np.int64(232), np.int64(233), np.int64(234), np.int64(235), np.int64(236), np.int64(238), np.int64(240), np.int64(242), np.int64(243), np.int64(244), np.int64(245), np.int64(246), np.int64(248), np.int64(251), np.int64(252), np.int64(253), np.int64(254), np.int64(257), np.int64(259), np.int64(260), np.int64(263), np.int64(264), np.int64(266), np.int64(267), np.int64(268), np.int64(269), np.int64(270), np.int64(272), np.int64(273), np.int64(274), np.int64(277), np.int64(279), np.int64(280), np.int64(283), np.int64(284), np.int64(285), np.int64(289), np.int64(290), np.int64(291), np.int64(292), np.int64(293), np.int64(295), np.int64(296), np.int64(297), np.int64(298), np.int64(299), np.int64(300), np.int64(301), np.int64(302), np.int64(303), np.int64(304), np.int64(305), np.int64(306), np.int64(307), np.int64(308), np.int64(309), np.int64(310), np.int64(312), np.int64(316), np.int64(318), np.int64(319), np.int64(321), np.int64(322), np.int64(323), np.int64(325), np.int64(326), np.int64(327), np.int64(328), np.int64(329), np.int64(330), np.int64(331), np.int64(332), np.int64(334), np.int64(335), np.int64(337), np.int64(338), np.int64(339), np.int64(343), np.int64(346), np.int64(348), np.int64(349), np.int64(350), np.int64(352), np.int64(353), np.int64(354), np.int64(355), np.int64(356), np.int64(357), np.int64(358), np.int64(360), np.int64(361), np.int64(362), np.int64(364), np.int64(365), np.int64(366), np.int64(367), np.int64(369), np.int64(370), np.int64(371), np.int64(372), np.int64(374), np.int64(375), np.int64(376)]: too few spikes (< 500).
  warnings.warn(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/quality/misc_metrics.py:1898: UserWarning: Only one bin is selected as the reference region, and thus the standard deviation cannot be computed. Please increase high_quantile. Setting noise cutoff to NaN
  warnings.warn(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/quality/misc_metrics.py:1909: UserWarning: All the high-amplitude bins have the same size. Please consider changing n_bins. Setting noise cutoff to NaN
  warnings.warn(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/quality/misc_metrics.py:1881: UserWarning: No bin is selected to test cutoff. Please increase low_quantile. Setting noise cutoff and ratio to NaN
  warnings.warn(
/mnt/Vol20tb1/yuxin/app/miniconda/envs/yuxin_mea/lib/python3.11/site-packages/spikeinterface/metrics/quality/misc_metrics.py:1892: UserWarning: No bin is selected as the reference region. Please increase high_quantile. Setting noise cutoff to NaN
  warnings.warn(

  ✓  54.0s  → analyzer_data/CX138/260329/T003346/Network/000029/rec0001/well008/analyzer

[auto_curation]  CX138/260329/T003346/Network/000029 / rec0001 / well008
  ✓  0.1s  → curation_data/CX138/260329/T003346/Network/000029/rec0001/well008/auto_curation

[burst_detection]  CX138/260329/T003346/Network/000029 / rec0001 / well008
  ✓  0.0s  → burst_detection_data/CX138/260329/T003346/Network/000029/rec0001/well008/burst_detection

[preprocessing]  CX138/260329/T003346/Network/000029 / rec0001 / well009
The h5 compression library for Maxwell is already located in /home/yuxin/hdf5_plugin_path_maxwell/libcompression.so!
write_zarr_recording
engine=process - n_jobs=30 - samples_per_chunk=10,000 - chunk_memory=25.18 MiB - total_memory=755.31 MiB - chunk_duration=1.00s

write_zarr_recording (workers: 30 processes fork):   0%|          | 0/301 [00:00<?, ?it/s]

## 5. Final status

In [ ]:
df_final = _pipeline_matrix(pipeline_mgr)

print("=== Per-task summary ===")
for task_name in TASK_ORDER:
    col = df_final[task_name]
    counts = col.value_counts().to_dict()
    print(f"  {task_name:<20s}  {counts}")

failed_mask = (df_final[TASK_ORDER] == "\u2717").any(axis=1)
if failed_mask.any():
    print("\n=== Failed wells ===")
    for _, row in df_final[failed_mask].iterrows():
        failed_tasks = [t for t in TASK_ORDER if row[t] == "\u2717"]
        print(f"  {row['recording_key']} / {row['rec_name']} / {row['well_id']}")
        print(f"    failed stages: {failed_tasks}")

print("\nLegend:  \u2014 not run   \u23f3 running   \u2713 complete   \u2717 failed")
df_final

=== Per-task summary ===
  preprocessing         {'—': 515, '✓': 13}
  sorting               {'—': 520, '✓': 8}
  auto_merge            {'—': 520, '✓': 8}
  analyzer              {'—': 520, '✓': 7, '⏳': 1}
  auto_curation         {'—': 521, '✗': 7}
  burst_detection       {'—': 528}

=== Failed wells ===
  CX138/260329/T003346/Network/000029 / rec0000 / well000
    failed stages: ['auto_curation']
  CX138/260329/T003346/Network/000029 / rec0000 / well001
    failed stages: ['auto_curation']
  CX138/260329/T003346/Network/000029 / rec0000 / well002
    failed stages: ['auto_curation']
  CX138/260329/T003346/Network/000029 / rec0000 / well003
    failed stages: ['auto_curation']
  CX138/260329/T003346/Network/000029 / rec0000 / well004
    failed stages: ['auto_curation']
  CX138/260329/T003346/Network/000029 / rec0000 / well005
    failed stages: ['auto_curation']
  CX138/260329/T003346/Network/000029 / rec0001 / well006
    failed stages: ['auto_curation']

Legend:  — not run   ⏳ running   ✓ complete   ✗ failed

,recording_key,rec_name,well_id,preprocessing,sorting,auto_merge,analyzer,auto_curation,burst_detection
0,CX138/260327/T003346/Network/000019,rec0000,well000,✓,—,—,—,—,—
1,CX138/260327/T003346/Network/000019,rec0000,well001,✓,—,—,—,—,—
2,CX138/260327/T003346/Network/000019,rec0000,well002,✓,—,—,—,—,—
3,CX138/260327/T003346/Network/000019,rec0000,well003,✓,—,—,—,—,—
4,CX138/260327/T003346/Network/000019,rec0000,well004,✓,—,—,—,—,—
...,...,...,...,...,...,...,...,...,...
523,CX138/260404/T003346/Network/000044,rec0003,well019,—,—,—,—,—,—
524,CX138/260404/T003346/Network/000044,rec0003,well020,—,—,—,—,—,—
525,CX138/260404/T003346/Network/000044,rec0003,well021,—,—,—,—,—,—
526,CX138/260404/T003346/Network/000044,rec0003,well022,—,—,—,—,—,—
527,CX138/260404/T003346/Network/000044,rec0003,well023,—,—,—,—,—,—

## 6. Curation summary

Reads `quality_metrics.parquet` from every completed `auto_curation` well
and produces an across-wells summary table.

In [1]:
summary_rows = []

for entry in pipeline_mgr.entries:
    curation_task = entry.tasks.get(AutoCurationTask.task_name)
    if not curation_task or curation_task.status != TaskStatus.COMPLETE:
        continue

    qm_path = Path(curation_task.output_path) / "quality_metrics.pkl"
    if not qm_path.exists():
        continue

    rec_name, well_id = entry.well_id.split("/", 1)
    qm = pd.read_pickle(qm_path)

    curated = qm[qm["curated"]]
    summary_rows.append({
        "recording_key": entry.recording_key,
        "rec_name":      rec_name,
        "well_id":       well_id,
        "n_total":        len(qm),
        "n_curated":      len(curated),
        "pct_kept":       round(100 * len(curated) / len(qm), 1) if len(qm) else 0,
        "median_fr_hz":   round(curated["firing_rate"].median(), 3)
                          if "firing_rate" in curated.columns and len(curated) else None,
        "median_amp_uv":  round(curated["amplitude_median"].median(), 1)
                          if "amplitude_median" in curated.columns and len(curated) else None,
    })

if summary_rows:
    df_curation = pd.DataFrame(summary_rows)
    print(f"Wells with curation results: {len(df_curation)}")
    print(f"Total curated units: {df_curation['n_curated'].sum()}  /  {df_curation['n_total'].sum()}")
    df_curation
else:
    print("No curation results yet — run the pipeline first.")

NameError: name 'pipeline_mgr' is not defined